// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbtcMy7O6Gu0h3_V4IzQSDJGh6Uk4uCYc',
    appId: '1:174743616791:web:49d6f9eef6aecff3d90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    authDomain: 'crossword-agent-8fad1.firebaseapp.com',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    measurementId: 'G-Y8DNED60Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgtoLCjFR3f9CVbH8BdWe4bcFgmVk5z1E',
    appId: '1:174743616791:android:7e4f5c85bb2f9e3dd90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDhXmfUgky83z-FH3BN8vLBrqLjgmcr4',
    appId: '1:174743616791:ios:62eea0d036e22f4ad90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    iosBundleId: 'com.example.workoutBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDhXmfUgky83z-FH3BN8vLBrqLjgmcr4',
    appId: '1:174743616791:ios:62eea0d036e22f4ad90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    iosBundleId: 'com.example.workoutBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbtcMy7O6Gu0h3_V4IzQSDJGh6Uk4uCYc',
    appId: '1:174743616791:web:b4b0dbcb04bcdcbcd90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    authDomain: 'crossword-agent-8fad1.firebaseapp.com',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    measurementId: 'G-ZZ408BYEHR',
  );
}
